/*
-- Query: SELECT * FROM goforgolddb.users
LIMIT 0, 1000

-- Date: 2025-12-15 20:18
*/
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (1,'Roseyn','Gozum','roseynreygozum@gmail.com',1,1,'$2b$10$ht2zQQ20x4B/Am/DXHf9HOgueX7vai9eQEVbWEsNkdrpAoarnJggG','100967831903848261900',NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (2,'John','Doe','jdoe@gmail.com',3,1,'$2b$10$/BZYWFwT.QH5FqrU8usTKuUOqITLbIYPjo6BCFkPhc//B6dZOOiSG',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (3,'Jane','Doe','jane@gmail.com',2,1,'$2b$10$Ja3RnhXdQxItdupcXLV4Zeb8yr.nzzsH28.AJmOLB5fLN7C5K0rZG',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (4,'Cordelia','Thomas','cthomas2026297@sjvhs.com',3,1,'$2b$10$CjOmpzPlTlswDQFnJrnxCeKrpKdnPqMlKDJiN4yJRMZhn5XzacfsW',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (5,'Rey','Gozum','rpgozum@gmail.com',3,1,'$2b$10$QUUlOb.A3oVyZqkGTlTnm.b0W1HTlx/FvNpk8fLQtjbuisQ543HOi',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (6,'Samantha','Farrugia','sfarrugia2026225@sjvhs.com',3,1,'$2b$10$o5C45nt3U53T9DXQyo6ve.oUSUlBCiSe1HuY5DtB0YMIfEqNxiT9q',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (7,'Rose','Gozum','regozum@gmail.com',3,1,'$2b$10$lZ0vlN7qs2qk0lVXmifFWOTB7VlBkFnBUXI1e97NMEyBbmP/oHBcO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (8,'Michela','Mungiello','mmungiello2026509@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (9,'Helen','Domashinski','hdomashinski2026177@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (10,'Susanna ','Matta','smatta2027315@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (11,'Sean ','Broderick','sbroderick2026085@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (12,'Grayson','Rispoli','grispoli2028601@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (13,'Riley ','Zergebel','rzergebel2026769@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (14,'Diana','Mackiewicz','dmackiewicz2026417@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (15,'Frank ','Puma','fpuma2028577@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (16,'Jacqueline','Farkas','jfarkas2026217@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (17,'Cooper','Symonds','csymonds2028717@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (18,'Nicholas','Lancia','nlancia2027270@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (19,'Violet','Mildenberg','vmildenberg2028473@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (20,'Emma','Chon','echon2028125@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (21,'Nora','Mullins','nmullins2027360@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (22,'Nikolas','Santos','nsantos2026609@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (23,'Danni','Struble','dstruble2025547@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (24,'Madi','Quinn','mquinn2025461@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (25,'Cara','Ventrudo','cventrudo2025583@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (26,'Catherine','Lee-Wells','snoopy2025blank@gmail.com',2,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (27,'Deborah','Piperno','homeworkclub2026@gmail.com',2,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (28,'Stephanie','Brogna','bowlingsjv202666@gmail.com',2,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (29,'Thomas','Mckenna','techsupport2625sjv@gmail.com',1,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (30,'Holly','Farro','hfarro2026221@sjvhs.com',3,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (31,'Christine','Fiorillo','theologyeca@gmail.coom',2,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (32,'Christopher','Scoles','blankemailtesting@gmail.com',1,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (33,'Daniel','Bielskie','mathclub202726@gmail.com',2,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (34,'Jennifer','Clifton','stemclubthursday2026@gmail.com',2,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
INSERT INTO `users` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (35,'Patrick','Smith','theologycac@gmail.com',2,1,'$2b$10$Wmi2vyfVFRhRPZU2w2T/Du5hSxLm4kMBUsCJiVoMc1OaZeAFbkjGO',NULL,NULL,NULL);
