/*
-- Query: SELECT * FROM goforgolddb.activities
LIMIT 0, 1000

-- Date: 2026-04-09 16:35
*/
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (1,'Drops of Rain',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (2,'Empowerment Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (3,'Animal Awareness Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (4,'More Than Special Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (5,'Blessing Bag Brigade',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (6,'History Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (7,'Homework Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (8,'Key Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (9,'Italian Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (10,'Fashion Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (11,'Lancers vs Cancer',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (12,'Chess Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (13,'Trailblazers (LL)',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (14,'Computer Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (15,'Investment Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (16,'Military Support Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (17,'Gardening Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (18,'Power Building Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (19,'Art Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (20,'Robotics Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (21,'Crochet Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (22,'Football Statistics Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (23,'Book Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (24,'Sustainability Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (25,'Light the Candle Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (26,'Social Justice Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (27,'Pre-Health Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (28,'Poetry/Creative Writing Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (29,'STEM Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (30,'Digital Photography Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (31,'Cultural Awareness & Latino Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (32,'Make a Difference Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (33,'Fishing Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (34,'Math Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (35,'Bible Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (36,'Book Buddy Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (37,'Model UN',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (38,'Film Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (39,'Closet Rewind Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (40,'Ping Pong Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (41,'Surfing Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (42,'Students for Life',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (43,'Steps for Success Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (44,'Football Statistics Club',4,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (45,'Football',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (46,'Boys\' Soccer',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (47,'Girls\' Soccer',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (48,'Field Hockey',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (49,'Girls\' Tennis',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (50,'Girls\' Volleyball',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (51,'Boys\' Cross Country',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (52,'Girls\' Cross Country',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (53,'Cheerleading',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (54,'Dance',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (55,'National Honor Society',5,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (103,'Gymnastics',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (104,'Girls\' Basketball',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (105,'Boys\' Basketball',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (106,'Wrestling',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (107,'Bowling',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (108,'Winter Track & Field',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (109,'Ice Hockey',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (110,'Swimming',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (111,'Softball',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (112,'Baseball',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (113,'Boys\' Golf',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (114,'Girls\' Golf',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (115,'Spring Track & Field',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (116,'Boys\' Lacrosse',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (117,'Girls\' Lacrosse',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (118,'Boys\' Volleyball',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (119,'Boys\' Tennis',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (120,'Girls\' Flag Football',1,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (121,'Polar Plunge',2,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (122,'Food Donations',2,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (123,'Junior Fundraiser',2,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (124,'Sophomore Fundraiser',2,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (125,'Freshman Fundraising',2,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (126,'Walk-a-Thon',2,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (127,'Actor - Fall Drama ',11,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (128,'Stage Crew - Fall Drama',11,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (129,'Actor - Spring Musical',11,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (130,'Stage Crew - Spring Musical',11,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (131,'Spanish Honor Society',5,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (132,'Italian Honor Society',5,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (133,'English Honor Society',5,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (134,'Tri-M Honor Society',5,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (135,'Art Honor Society',5,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (136,'Quill & Scroll Honor Society',5,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (137,'Ambassador Club',3,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (138,'ECA Parent Meeting',3,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (139,'SJV Student Event - Set Up',3,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (140,'SJV Student Event - Break Down',3,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (141,'Class of 2026',7,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (142,'Class of 2027',7,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (143,'Class of 2028',7,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (144,'Class of 2029',7,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (145,'Yearbook Editor',6,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (146,'Creative Writing Publication',6,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (147,'Student of the Month - September',12,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (148,'Student of the Month - October',12,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (149,'Student of the Month - November',12,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (150,'Student of the Month - December',12,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (151,'Student of the Month - January',12,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (152,'Student of the Month - February',12,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (153,'Student of the Month - March',12,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (154,'Student of the Month - April',12,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (155,'Student of the Month - May',12,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (156,'Mock Trial',13,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (157,'Entrepreneurship Team',13,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (158,'Rock Band',3,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (159,'Choir',14,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (160,'Sound & Tech Team',14,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (161,'Altar Server',14,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (162,'Eucharistic Minister',14,1);
INSERT INTO `` (`activity_id`,`activity_name`,`category_id`,`active`) VALUES (163,'Reader',14,1);
