/*
-- Query: SELECT * FROM goforgolddb.users
LIMIT 0, 1000

-- Date: 2026-04-09 20:22
*/
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (1,'Roseyn','Gozum','roseynreygozum@gmail.com',1,1,'$2b$10$oXLwW3JxvS5R/MY0FT.on.QKdqwno6iKpbd6KQxNEDjiQHI2DSIQG','100967831903848261900',NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (2,'John','Doe','jdoe@gmail.com',3,1,'$2b$10$Bi14A8VO/bwoF2FkX2GucOnvFtv01SAaB7UV5InKYmem9sy6dc/2.',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (3,'Jane','Doe','jane@gmail.com',1,1,'$2b$10$Bi14A8VO/bwoF2FkX2GucOnvFtv01SAaB7UV5InKYmem9sy6dc/2.',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (4,'Cordelia','Thomas','cthomas2026297@sjvhs.com',3,1,'$2b$10$CjOmpzPlTlswDQFnJrnxCeKrpKdnPqMlKDJiN4yJRMZhn5XzacfsW',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (5,'Rey','Gozum','rpgozum@gmail.com',3,1,'$2b$10$QUUlOb.A3oVyZqkGTlTnm.b0W1HTlx/FvNpk8fLQtjbuisQ543HOi',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (37,'Michela','Mungiello','mmungiello2026509@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (38,'Helen','Domashinski','hdomashinski2026177@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (39,'Susanna ','Matta','smatta2027315@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (40,'Sean ','Broderick','sbroderick2026085@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (41,'Grayson','Rispoli','grispoli2028601@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (42,'Riley ','Zergebel','rzergebel2026769@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (43,'Diana','Mackiewicz','dmackiewicz2026417@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (44,'Frank ','Puma','fpuma2028577@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (45,'Jacqueline','Farkas','jfarkas2026217@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (46,'Cooper','Symonds','csymonds2028717@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (47,'Nicholas','Lancia','nlancia2027270@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (48,'Violet','Mildenberg','vmildenberg2028473@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (49,'Emma','Chon','echon2028125@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (50,'Nora','Mullins','nmullins2027360@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (51,'Nikolas','Santos','nsantos2026609@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (52,'Danni','Struble','dstruble2025547@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (53,'Madi','Quinn','mquinn2025461@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (54,'Cara','Ventrudo','cventrudo2025583@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (55,'Catherine','Lee-Wells','snoopy2025blank@gmail.com',2,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (56,'Deborah','Piperno','homeworkclub2026@gmail.com',2,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (57,'Stephanie','Brogna','bowlingsjv202666@gmail.com',2,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (58,'Thomas','Mckenna','techsupport2625sjv@gmail.com',1,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (59,'Holly','Farro','hfarro2026221@sjvhs.com',3,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (60,'Christine','Fiorillo','theologyeca@gmail.com',2,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (61,'Christopher','Scoles','blankemailtesting@gmail.com',1,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (62,'Daniel','Bielskie','mathclub202726@gmail.com',2,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (63,'Jennifer','Clifton','stemclubthursday2026@gmail.com',2,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
INSERT INTO `` (`user_id`,`first_name`,`last_name`,`email_address`,`user_role_id`,`active`,`password`,`google_id`,`token`,`token_created_at`) VALUES (64,'Patrick','Smith','theologycac@gmail.com',2,1,'$2b$10$GX39VmkTL/GxGye7B8DG7OTFxmJeBgu24Rdc.YIu.3/xY.JTA83kq',NULL,NULL,NULL);
